CREATE TABLE IF NOT EXISTS products (
    id SERIAL PRIMARY KEY,
    campo1 VARCHAR(255) NOT NULL,
    campo2 VARCHAR(255) NOT NULL,
    campo3 VARCHAR(255) NOT NULL,
    campo4 INTEGER NOT NULL,
    campo5 NUMERIC NOT NULL,
    campo6 BOOLEAN NOT NULL
);